### PR TITLE
Preserve user-customized p/i/.htaccess and .htpasswd across ZIP updates

### LINKED ISSUE #6584: [Bug] Webupdater deletes /p/i/.htaccess file
### Describe the bug

I'm using .htaccess for http-auth mentioned [here](https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html). My authorization settings use OpenLDAP, so I do not use the .htpasswd file. During the webupdate, the .htaccess file, located in /p/i/, with my own settings is deleted, which causes an access failure error (503) to appear immediately after update process. It is also possible that the update is interrupted at some point because of this.

### To Reproduce

1. Set user authentication via http auth in the /p/i/.htaccess file
2. Update FreshRSS from the subpage: /i/?c=update.

### Expected behavior

The update completes successfully and the /p/i/.htaccess file is preserved.

### FreshRSS version

1.24.0, 1.24.1

### Environment information

Debian 12,  Apache/2.4.59, PHP 8.3, MySQL, no Docker

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by polybjorn**
Fixes FreshRSS/FreshRSS#6584

## Problem

`deploy_package()` calls `del_tree(PUBLIC_PATH)` before `recurse_copy(... '/p', PUBLIC_PATH)`, which removes any user-created file under `p/` - including the `p/i/.htaccess` used for HTTP-auth setups (LDAP, htpasswd, etc.) documented at https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html. Users with HTTP-auth are locked out immediately after the web update.

The lockout also prevents the post-update request from running, so `data/update.php` lingers and FreshRSS keeps showing "update pending" - second symptom reported in the same issue.

## Fix

Mirrors the existing `save_custom_themes()` pattern: stage the user's auth files into the new package tree before the wipe, so the subsequent `recurse_copy` restores them. No change to the wipe-and-recopy architecture, no change to orphan cleanup, no rollback logic needed.

File mode is preserved explicitly via `chmod` after `copy()` - matters for `.htpasswd`, where PHP's default `copy()` would otherwise widen 0640 to 0644.

## Limitations

- If FreshRSS ever ships a non-trivial change to the default `p/i/.htaccess`, customized installs will silently keep their old version. Same tradeoff `save_custom_themes` already accepts for `xTheme-*` directories. A proper fix would need a per-release manifest of shipped file hashes (coordinated change in the main FreshRSS repo) - happy to do that as a follow-up if preferred.
- A symlinked `p/i/.htaccess` (uncommon - some admins centrally manage it via symlink) is replaced with a regular file copy. Content is preserved; the symlink relationship is not. Fixing this would require changes to `recurse_copy` or a separate post-deploy restore path; not worth the dual-code-path cost given no reports of this case.

## Testing

Verified in isolation against seven scenarios:
- LDAP case (custom `.htaccess`, no `.htpasswd`)
- Basic-auth case (both files customized)
- Vanilla install (no customization, shipped defaults untouched)
- Full `save → del_tree → recurse_copy` slice end-to-end
- Empty `.htaccess`
- File mode preservation on `.htpasswd` (0640 source → 0640 destination)
- Symlinked `.htaccess` (content preserved, becomes regular file)

`phpcs --standard=phpcs.xml` shows 0 new violations on the changed lines.

Did not run against a live ZIP install.

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Plus it's suggested that way in the docs: <https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html#http-authentication>.

File: scripts/update_util.php [hunk 1]
```diff
@@ -150,13 +150,29 @@ function save_custom_themes($destination) {
 }
 
 
+// Preserve custom auth files to not delete them
+function save_custom_auth($destination) {
```
Comment (Alkarex) [inline scripts/update_util.php]:
```suggestion
function save_custom_auth(string $destination) {
```

File: scripts/update_util.php [hunk 2]
```diff
@@ -150,13 +150,29 @@ function save_custom_themes($destination) {
...
+	$auth_dir = PUBLIC_PATH . '/i';
+	foreach (array('.htaccess', '.htpasswd') as $filename) {
```
Comment (Alkarex) [inline scripts/update_util.php]:
```suggestion
	foreach (['.htaccess', '.htpasswd'] as $filename) {
```

File: scripts/update_util.php [hunk 3]
```diff
@@ -150,13 +150,29 @@ function save_custom_themes($destination) {
...
+		$src = $auth_dir . '/' . $filename;
+		if (is_file($src)) {
+			$dst = $destination . '/' . $filename;
+			$mode = fileperms($src) & 0777;
```
Comment (Alkarex) [inline scripts/update_util.php]:
```suggestion
			$mode = fileperms($src) & 0777;	// Mask to keep only the permission bits
```
